# Comprehensive gazetteers for India-specific entity matching
# Extended lists for better coverage

STATES_UTS = [
    "Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat",
    "Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh",
    "Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab",
    "Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand",
    "West Bengal","Andaman and Nicobar Islands","Chandigarh","Dadra and Nagar Haveli and Daman and Diu",
    "Delhi","Jammu and Kashmir","Ladakh","Lakshadweep","Puducherry",
    # Common abbreviations
    "AP", "HP", "MP", "UP", "UK", "WB", "TN", "J&K"
]

MINISTRIES = [
    # English - All 40+ Central Ministries
    "Ministry of Health and Family Welfare", "Ministry of Education",
    "Ministry of Agriculture and Farmers Welfare", "Ministry of Finance",
    "Ministry of Home Affairs", "Ministry of External Affairs", "Ministry of Defence",
    "Ministry of Environment, Forest and Climate Change",
    "Ministry of Road Transport and Highways", "Ministry of Railways",
    "Ministry of Electronics and Information Technology",
    "Ministry of Women and Child Development", "Ministry of Rural Development",
    "Ministry of Power", "Ministry of New and Renewable Energy",
    "Ministry of Commerce and Industry", "Ministry of Labour and Employment",
    "Ministry of Social Justice and Empowerment", "Ministry of Tribal Affairs",
    "Ministry of Culture", "Ministry of Tourism", "Ministry of Civil Aviation",
    "Ministry of Ports, Shipping and Waterways", "Ministry of Science and Technology",
    "Ministry of Skill Development and Entrepreneurship", "Ministry of Law and Justice",
    "Ministry of Parliamentary Affairs", "Ministry of Minority Affairs",
    "Ministry of Housing and Urban Affairs", "Ministry of Jal Shakti",
    "Ministry of Food Processing Industries", "Ministry of AYUSH", "Ministry of Textiles",
    "Ministry of Steel", "Ministry of Mines", "Ministry of Petroleum and Natural Gas",
    "Ministry of Coal", "Ministry of Statistics and Programme Implementation",
    "Ministry of Corporate Affairs", "Ministry of Consumer Affairs, Food and Public Distribution",
    "Ministry of Cooperation", "Ministry of Fisheries, Animal Husbandry and Dairying",
    "Ministry of Earth Sciences", "Ministry of Chemicals and Fertilizers",
    "Ministry of Micro, Small and Medium Enterprises", "Ministry of Development of North Eastern Region",
    "Ministry of Panchayati Raj", "Ministry of Information and Broadcasting",
    "NITI Aayog", "Prime Minister's Office", "PMO", "Cabinet Secretariat",
    
    # Hindi - सभी मंत्रालय
    "गृह मंत्रालय", "विदेश मंत्रालय", "वित्त मंत्रालय", "रक्षा मंत्रालय",
    "स्वास्थ्य और परिवार कल्याण मंत्रालय", "शिक्षा मंत्रालय", "कृषि मंत्रालय",
    "रेल मंत्रालय", "सड़क परिवहन और राजमार्ग मंत्रालय", "इलेक्ट्रॉनिक्स और सूचना प्रौद्योगिकी मंत्रालय",
    "महिला और बाल विकास मंत्रालय", "ग्रामीण विकास मंत्रालय", "ऊर्जा मंत्रालय",
    "नवीन और नवीकरणीय ऊर्जा मंत्रालय", "वाणिज्य और उद्योग मंत्रालय",
    "श्रम और रोजगार मंत्रालय", "सामाजिक न्याय और अधिकारिता मंत्रालय",
    "जनजातीय मामलों का मंत्रालय", "संस्कृति मंत्रालय", "पर्यटन मंत्रालय",
    "नागरिक उड्डयन मंत्रालय", "बंदरगाह, जहाजरानी और जलमार्ग मंत्रालय",
    "विज्ञान और प्रौद्योगिकी मंत्रालय", "कौशल विकास और उद्यमिता मंत्रालय",
    "विधि और न्याय मंत्रालय", "संसदीय कार्य मंत्रालय", "अल्पसंख्यक मामलों का मंत्रालय",
    "आवास और शहरी मामलों का मंत्रालय", "जल शक्ति मंत्रालय",
    "खाद्य प्रसंस्करण उद्योग मंत्रालय", "आयुष मंत्रालय", "वस्त्र मंत्रालय",
    "इस्पात मंत्रालय", "खान मंत्रालय", "पेट्रोलियम और प्राकृतिक गैस मंत्रालय",
    "कोयला मंत्रालय", "पर्यावरण, वन और जलवायु परिवर्तन मंत्रालय",
    "सूचना और प्रसारण मंत्रालय", "नीति आयोग", "प्रधानमंत्री कार्यालय", "पीएमओ",
    
    # Kannada - ಎಲ್ಲಾ ಸಚಿವಾಲಯಗಳು
    "ಗೃಹ ಸಚಿವಾಲಯ", "ವಿದೇಶಾಂಗ ಸಚಿವಾಲಯ", "ಹಣಕಾಸು ಸಚಿವಾಲಯ", "ರಕ್ಷಣಾ ಸಚಿವಾಲಯ",
    "ಆರೋಗ್ಯ ಮತ್ತು ಕುಟುಂಬ ಕಲ್ಯಾಣ ಸಚಿವಾಲಯ", "ಶಿಕ್ಷಣ ಸಚಿವಾಲಯ", "ಕೃಷಿ ಸಚಿವಾಲಯ",
    "ರೈಲ್ವೆ ಸಚಿವಾಲಯ", "ರಸ್ತೆ ಸಾರಿಗೆ ಮತ್ತು ಹೆದ್ದಾರಿ ಸಚಿವಾಲಯ",
    "ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಮತ್ತು ಮಾಹಿತಿ ತಂತ್ರಜ್ಞಾನ ಸಚಿವಾಲಯ",
    "ಮಹಿಳೆಯರ ಮತ್ತು ಮಕ್ಕಳ ಅಭಿವೃದ್ಧಿ ಸಚಿವಾಲಯ", "ಗ್ರಾಮೀಣ ಅಭಿವೃದ್ಧಿ ಸಚಿವಾಲಯ",
    "ವಿದ್ಯುತ್ ಸಚಿವಾಲಯ", "ಹೊಸ ಮತ್ತು ನವೀಕರಿಸಬಹುದಾದ ಇಂಧನ ಸಚಿವಾಲಯ",
    "ವಾಣಿಜ್ಯ ಮತ್ತು ಕೈಗಾರಿಕೆ ಸಚಿವಾಲಯ", "ಕಾರ್ಮಿಕ ಮತ್ತು ಉದ್ಯೋಗ ಸಚಿವಾಲಯ",
    "ಸಾಮಾಜಿಕ ನ್ಯಾಯ ಮತ್ತು ಅಧಿಕಾರ ಸಚಿವಾಲಯ", "ಪರಿಸರ ಸಚಿವಾಲಯ",
    "ನೀತಿ ಆಯೋಗ", "ಪ್ರಧಾನಿ ಕಛೇರಿ",
    
    # Tamil - அனைத்து அமைச்சகங்கள்
    "உள்துறை அமைச்சகம்", "வெளியுறவு அமைச்சகம்", "நிதி அமைச்சகம்", "பாதுகாப்பு அமைச்சகம்",
    "சுகாதாரம் மற்றும் குடும்ப நல அமைச்சகம்", "கல்வி அமைச்சகம்", "வேளாண்மை அமைச்சகம்",
    "ரயில்வே அமைச்சகம்", "சாலை போக்குவரத்து மற்றும் நெடுஞ்சாலைகள் அமைச்சகம்",
    "மின்னணுவியல் மற்றும் தகவல் தொழில்நுட்ப அமைச்சகம்",
    "மகளிர் மற்றும் குழந்தைகள் மேம்பாட்டு அமைச்சகம்", "கிராமப்புற மேம்பாட்டு அமைச்சகம்",
    "மின்சார அமைச்சகம்", "வர்த்தகம் மற்றும் தொழில் அமைச்சகம்",
    "சுற்றுச்சூழல் அமைச்சகம்", "நீதி அயோக்", "பிரதமர் அலுவலகம்",
    
    # Telugu - అన్ని మంత్రిత్వ శాఖలు
    "హోం వ్యవహారాల మంత్రిత్వ శాఖ", "విదేశీ వ్యవహారాల మంత్రిత్వ శాఖ",
    "ఆర్థిక మంత్రిత్వ శాఖ", "రక్షణ మంత్రిత్వ శాఖ",
    "ఆరోగ్యం మరియు కుటుంబ సంక్షేమ మంత్రిత్వ శాఖ", "విద్యా మంత్రిత్వ శాఖ",
    "వ్యవసాయ మంత్రిత్వ శాఖ", "రైల్వే మంత్రిత్వ శాఖ",
    "రహదారి రవాణా మరియు రహదారుల మంత్రిత్వ శాఖ",
    "ఎలక్ట్రానిక్స్ మరియు సమాచార సాంకేతిక మంత్రిత్వ శాఖ",
    "మహిళా మరియు పిల్లల అభివృద్ధి మంత్రిత్వ శాఖ", "గ్రామీణాభివృద్ధి మంత్రిత్వ శాఖ",
    "విద్యుత్ మంత్రిత్వ శాఖ", "వాణిజ్యం మరియు పరిశ్రమల మంత్రిత్వ శాఖ",
    "నీతి ఆయోగ్", "ప్రధాని కార్యాలయం",
    
    # Bengali - সকল মন্ত্রণালয়
    "স্বরাষ্ট্র মন্ত্রণালয়", "পররাষ্ট্র মন্ত্রণালয়", "অর্থ মন্ত্রণালয়", "প্রতিরক্ষা মন্ত্রণালয়",
    "স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রণালয়", "শিক্ষা মন্ত্রণালয়", "কৃষি মন্ত্রণালয়",
    "রেল মন্ত্রণালয়", "সড়ক পরিবহন ও মহাসড়ক মন্ত্রণালয়",
    "ইলেকট্রনিক্স ও তথ্য প্রযুক্তি মন্ত্রণালয়",
    "মহিলা ও শিশু উন্নয়ন মন্ত্রণালয়", "গ্রামীণ উন্নয়ন মন্ত্রণালয়",
    "বিদ্যুৎ মন্ত্রণালয়", "বাণিজ্য ও শিল্প মন্ত্রণালয়",
    "নীতি আয়োগ", "প্রধানমন্ত্রীর কার্যালয়",
    
    # Malayalam - എല്ലാ മന്ത്രാലയങ്ങളും
    "ആഭ്യന്തര മന്ത്രാലയം", "വിദേശകാര്യ മന്ത്രാലയം", "ധനമന്ത്രാലയം", "പ്രതിരോധ മന്ത്രാലയം",
    "ആരോഗ്യ കുടുംബക്ഷേമ മന്ത്രാലയം", "വിദ്യാഭ്യാസ മന്ത്രാലയം", "കാർഷിക മന്ത്രാലയം",
    "റയിൽവേ മന്ത്രാലയം", "റോഡ് ഗതാഗത ഹൈവേ മന്ത്രാലയം",
    "ഇലക്ട്രോണിക്സ് ഐടി മന്ത്രാലയം", "വനിതാ ശിശു വികസന മന്ത്രാലയം",
    "ഗ്രാമവികസന മന്ത്രാലയം", "വൈദ്യുതി മന്ത്രാലയം",
    "നീതി ആയോഗ്", "പ്രധാനമന്ത്രി ഓഫീസ്",
    
    # Marathi - सर्व मंत्रालये
    "गृह मंत्रालय", "परराष्ट्र मंत्रालय", "वित्त मंत्रालय", "संरक्षण मंत्रालय",
    "आरोग्य आणि कुटुंब कल्याण मंत्रालय", "शिक्षण मंत्रालय", "कृषी मंत्रालय",
    "रेल्वे मंत्रालय", "रस्ते वाहतूक आणि महामार्ग मंत्रालय",
    "इलेक्ट्रॉनिक्स आणि माहिती तंत्रज्ञान मंत्रालय",
    "महिला आणि बाल विकास मंत्रालय", "ग्रामीण विकास मंत्रालय",
    "ऊर्जा मंत्रालय", "वाणिज्य आणि उद्योग मंत्रालय",
    "नीती आयोग", "पंतप्रधान कार्यालय",
    
    # Gujarati - તમામ મંત્રાલયો
    "ગૃહ મંત્રાલય", "વિદેશ મંત્રાલય", "નાણા મંત્રાલય", "સંરક્ષણ મંત્રાલય",
    "આરોગ્ય અને કુટુંબ કલ્યાણ મંત્રાલય", "શિક્ષણ મંત્રાલય", "કૃષિ મંત્રાલય",
    "રેલવે મંત્રાલય", "માર્ગ પરિવહન અને હાઇવે મંત્રાલય",
    "ઇલેક્ટ્રોનિક્સ અને આઇટી મંત્રાલય", "મહિલા અને બાળ વિકાસ મંત્રાલય",
    "ગ્રામ્ય વિકાસ મંત્રાલય", "ઊર્જા મંત્રાલય",
    "નીતિ આયોગ", "વડાપ્રધાન કાર્યાલય",
    
    # Punjabi - ਸਾਰੇ ਮੰਤਰਾਲੇ
    "ਗ੍ਰਹਿ ਮੰਤਰਾਲਾ", "ਵਿਦੇਸ਼ ਮੰਤਰਾਲਾ", "ਵਿੱਤ ਮੰਤਰਾਲਾ", "ਰੱਖਿਆ ਮੰਤਰਾਲਾ",
    "ਸਿਹਤ ਅਤੇ ਪਰਿਵਾਰ ਭਲਾਈ ਮੰਤਰਾਲਾ", "ਸਿੱਖਿਆ ਮੰਤਰਾਲਾ", "ਖੇਤੀਬਾੜੀ ਮੰਤਰਾਲਾ",
    "ਰੇਲਵੇ ਮੰਤਰਾਲਾ", "ਸੜਕ ਆਵਾਜਾਈ ਅਤੇ ਹਾਈਵੇਅ ਮੰਤਰਾਲਾ",
    "ਇਲੈਕਟ੍ਰੌਨਿਕਸ ਅਤੇ ਆਈਟੀ ਮੰਤਰਾਲਾ", "ਔਰਤਾਂ ਅਤੇ ਬੱਚਿਆਂ ਦੀ ਤਰੱਕੀ ਮੰਤਰਾਲਾ",
    "ਪੇਂਡੂ ਵਿਕਾਸ ਮੰਤਰਾਲਾ", "ਊਰਜਾ ਮੰਤਰਾਲਾ",
    "ਨੀਤੀ ਆਯੋਗ", "ਪ੍ਰਧਾਨ ਮੰਤਰੀ ਦਫਤਰ",
    
    # Odia - ସମସ୍ତ ମନ୍ତ୍ରଣାଳୟ
    "ଗୃହ ମନ୍ତ୍ରଣାଳୟ", "ବୈଦେଶିକ ମନ୍ତ୍ରଣାଳୟ", "ଅର୍ଥ ମନ୍ତ୍ରଣାଳୟ", "ପ୍ରତିରକ୍ଷା ମନ୍ତ୍ରଣାଳୟ",
    "ସ୍ୱାସ୍ଥ୍ୟ ଏବଂ ପରିବାର କଲ୍ୟାଣ ମନ୍ତ୍ରଣାଳୟ", "ଶିକ୍ଷା ମନ୍ତ୍ରଣାଳୟ", "କୃଷି ମନ୍ତ୍ରଣାଳୟ",
    "ରେଳବାଇ ମନ୍ତ୍ରଣାଳୟ", "ସଡକ ପରିବହନ ଏବଂ ରାଜପଥ ମନ୍ତ୍ରଣାଳୟ",
    "ଇଲେକ୍ଟ୍ରୋନିକ୍ସ ଏବଂ ଆଇଟି ମନ୍ତ୍ରଣାଳୟ", "ମହିଳା ଏବଂ ଶିଶୁ ବିକାଶ ମନ୍ତ୍ରଣାଳୟ",
    "ଗ୍ରାମୀଣ ବିକାଶ ମନ୍ତ୍ରଣାଳୟ", "ଶକ୍ତି ମନ୍ତ୍ରଣାଳୟ",
    "ନୀତି ଆୟୋଗ", "ପ୍ରଧାନମନ୍ତ୍ରୀ କାର୍ଯ୍ୟାଳୟ",
]

SCHEMES = [
    # English - All Major Central Government Schemes
    "Ayushman Bharat", "PM-KISAN", "Pradhan Mantri Kisan Samman Nidhi",
    "PM Ujjwala Yojana", "Ujjwala", "Swachh Bharat Mission", "Swachh Bharat Abhiyan",
    "Swachh Bharat", "Atal Pension Yojana", "APY", "Digital India", "Make in India",
    "Smart Cities Mission", "Smart City", "PMAY", "Pradhan Mantri Awas Yojana",
    "PM Awas Yojana", "PM Fasal Bima Yojana", "PMFBY", "Crop Insurance",
    "Jal Jeevan Mission", "Har Ghar Jal", "Mahatma Gandhi National Rural Employment Guarantee Act",
    "MGNREGA", "NREGA", "MNREGA", "Pradhan Mantri Mudra Yojana", "MUDRA Yojana",
    "MUDRA", "Stand Up India", "Startup India", "Skill India", "Beti Bachao Beti Padhao",
    "BBBP", "Sukanya Samriddhi Yojana", "SSY", "National Health Mission", "NHM",
    "PM Garib Kalyan Anna Yojana", "PM Garib Kalyan Yojana", "PMGKAY",
    "One Nation One Ration Card", "ONORC", "Atmanirbhar Bharat", "Self-Reliant India",
    "Aatmanirbhar", "Production Linked Incentive", "PLI Scheme", "PLI",
    "PM Gati Shakti", "PM GatiShakti National Master Plan", "Gati Shakti",
    "National Education Policy", "NEP 2020", "NEP", "PM-CARES Fund", "PM CARES", "PMCARES",
    "PM Street Vendor's AtmaNirbhar Nidhi", "PM SVANidhi", "SVANidhi",
    "Pradhan Mantri Jan Dhan Yojana", "PM-JDY", "Jan Dhan", "PMJDY",
    "PM-JAY", "Ayushman Bharat PM-JAY", "Pradhan Mantri Matru Vandana Yojana", "PMMVY",
    "Pradhan Mantri Suraksha Bima Yojana", "PMSBY", "Pradhan Mantri Jeevan Jyoti Bima Yojana",
    "PMJJBY", "PM Kisan Maandhan Yojana", "PM-KMY", "PM Shram Yogi Maandhan Yojana",
    "PM-SYM", "Kisan Credit Card", "KCC", "Namami Gange", "Clean Ganga Mission",
    "Ganga Mission", "UDAN", "Ude Desh ka Aam Naagrik", "Regional Connectivity Scheme",
    "Saubhagya Yojana", "Pradhan Mantri Sahaj Bijli Har Ghar Yojana", "Saubhagya",
    "Khelo India", "Khelo India Scheme", "PM Jan Aushadhi Yojana", "PMBJP",
    "Jan Aushadhi", "PM Vishwakarma Yojana", "PM Vishwakarma Kaushal Samman",
    "PM Vishwakarma", "Vande Bharat Express", "Vande Bharat", "Ayushman Bharat Digital Mission",
    "ABDM", "Amrit Bharat Station Scheme", "Amrit Bharat", "PM POSHAN",
    "PM Poshan Shakti Nirman", "National Apprenticeship Promotion Scheme", "NAPS",
    "FAME India", "Faster Adoption of Electric Vehicles", "FAME",
    "Ek Bharat Shrestha Bharat", "Fit India Movement", "Fit India",
    "Ujala Yojana", "UJALA", "LED Bulb Scheme", "Sagarmala Project", "Sagarmala",
    "Bharatmala Pariyojana", "Bharatmala", "Pradhan Mantri Gram Sadak Yojana",
    "PMGSY", "Gram Sadak", "Deendayal Antyodaya Yojana", "DAY-NULM", "DAY-NRLM",
    "National Rural Livelihood Mission", "NRLM", "Pradhan Mantri Kaushal Vikas Yojana",
    "PMKVY", "Skill Development", "Samagra Shiksha Abhiyan", "Samagra Shiksha",
    "Mid Day Meal Scheme", "PM CARES for Children", "Har Ghar Nal", "Jal Shakti Abhiyan",
    "AMRUT Mission", "Atal Mission for Rejuvenation and Urban Transformation", "AMRUT",
    "HRIDAY", "Heritage City Development", "Swadesh Darshan", "Pilgrimage Rejuvenation",
    "Namami Gange", "National Mission for Clean Ganga", "PM-KUSUM", "Solar Pump",
    "KUSUM Yojana", "Rythu Bandhu", "PM-KISAN Samman", "Kisan Samman Nidhi",
    
    # Hindi - सभी योजनाएं
    "आयुष्मान भारत", "पीएम किसान", "प्रधानमंत्री किसान सम्मान निधि", "किसान सम्मान निधि",
    "पीएम उज्ज्वला योजना", "उज्ज्वला योजना", "स्वच्छ भारत मिशन", "स्वच्छ भारत अभियान",
    "स्वच्छ भारत", "अटल पेंशन योजना", "डिजिटल इंडिया", "मेक इन इंडिया",
    "स्मार्ट सिटी मिशन", "स्मार्ट सिटी", "पीएमएवाई", "प्रधानमंत्री आवास योजना",
    "पीएम आवास योजना", "प्रधानमंत्री फसल बीमा योजना", "फसल बीमा",
    "जल जीवन मिशन", "हर घर जल", "महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम",
    "मनरेगा", "नरेगा", "प्रधानमंत्री मुद्रा योजना", "मुद्रा योजना",
    "स्टैंड अप इंडिया", "स्टार्टअप इंडिया", "स्किल इंडिया", "कौशल भारत",
    "बेटी बचाओ बेटी पढ़ाओ", "सुकन्या समृद्धि योजना", "राष्ट्रीय स्वास्थ्य मिशन",
    "पीएम गरीब कल्याण अन्न योजना", "पीएम गरीब कल्याण योजना",
    "एक राष्ट्र एक राशन कार्ड", "आत्मनिर्भर भारत", "आत्मनिर्भर भारत अभियान",
    "उत्पादन संबद्ध प्रोत्साहन योजना", "पीएलआई योजना",
    "पीएम गति शक्ति", "गति शक्ति", "राष्ट्रीय शिक्षा नीति", "एनईपी 2020",
    "पीएम केयर्स फंड", "पीएम केयर्स", "पीएम स्वनिधि", "स्वनिधि योजना",
    "प्रधानमंत्री जन धन योजना", "जन धन योजना", "जन धन",
    "प्रधानमंत्री मातृ वंदना योजना", "प्रधानमंत्री सुरक्षा बीमा योजना",
    "प्रधानमंत्री जीवन ज्योति बीमा योजना", "पीएम किसान मानधन योजना",
    "पीएम श्रम योगी मानधन योजना", "किसान क्रेडिट कार्ड",
    "नमामि गंगे", "स्वच्छ गंगा मिशन", "उड़ान योजना", "उड़े देश का आम नागरिक",
    "सौभाग्य योजना", "खेलो इंडिया", "पीएम जन औषधि योजना", "जन औषधि",
    "पीएम विश्वकर्मा योजना", "वंदे भारत एक्सप्रेस", "वंदे भारत",
    "आयुष्मान भारत डिजिटल मिशन", "अमृत भारत स्टेशन योजना",
    "पीएम पोषण", "पीएम पोषण शक्ति निर्माण", "एक भारत श्रेष्ठ भारत",
    "फिट इंडिया", "उजाला योजना", "सागरमाला परियोजना", "भारतमाला परियोजना",
    "प्रधानमंत्री ग्राम सड़क योजना", "दीनदयाल अंत्योदय योजना",
    "प्रधानमंत्री कौशल विकास योजना", "समग्र शिक्षा अभियान", "मिड डे मील योजना",
    
    # Kannada - ಎಲ್ಲಾ ಯೋಜನೆಗಳು
    "ಆಯುಷ್ಮಾನ್ ಭಾರತ", "ಪಿಎಂ ಕಿಸಾನ್", "ಪ್ರಧಾನಮಂತ್ರಿ ಕಿಸಾನ್ ಸಮ್ಮಾನ್ ನಿಧಿ",
    "ಪಿಎಂ ಉಜ್ವಲಾ ಯೋಜನೆ", "ಸ್ವಚ್ಛ ಭಾರತ ಮಿಷನ್", "ಸ್ವಚ್ಛ ಭಾರತ ಅಭಿಯಾನ",
    "ಸ್ವಚ್ಛ ಭಾರತ", "ಅಟಲ್ ಪಿಂಚಣಿ ಯೋಜನೆ", "ಡಿಜಿಟಲ್ ಇಂಡಿಯಾ", "ಮೇಕ್ ಇನ್ ಇಂಡಿಯಾ",
    "ಸ್ಮಾರ್ಟ್ ಸಿಟಿ ಮಿಷನ್", "ಪ್ರಧಾನಮಂತ್ರಿ ಆವಾಸ ಯೋಜನೆ",
    "ಫಸಲ್ ಬೀಮಾ ಯೋಜನೆ", "ಜಲ್ ಜೀವನ್ ಮಿಷನ್", "ಹರ್ ಘರ್ ಜಲ್",
    "ಮಹಾತ್ಮಾ ಗಾಂಧಿ ರಾಷ್ಟ್ರೀಯ ಗ್ರಾಮೀಣ ಉದ್ಯೋಗ ಖಾತರಿ ಕಾಯ್ದೆ",
    "ಮನರೇಗಾ", "ಪ್ರಧಾನಮಂತ್ರಿ ಮುದ್ರಾ ಯೋಜನೆ", "ಸ್ಟ್ಯಾಂಡ್ ಅಪ್ ಇಂಡಿಯಾ",
    "ಸ್ಟಾರ್ಟಪ್ ಇಂಡಿಯಾ", "ಸ್ಕಿಲ್ ಇಂಡಿಯಾ", "ಬೆಟಿ ಬಚಾವೋ ಬೆಟಿ ಪಢಾವೋ",
    "ಸುಕನ್ಯಾ ಸಮೃದ್ಧಿ ಯೋಜನೆ", "ರಾಷ್ಟ್ರೀಯ ಆರೋಗ್ಯ ಮಿಷನ್",
    "ಪಿಎಂ ಗರೀಬ್ ಕಲ್ಯಾಣ ಅನ್ನ ಯೋಜನೆ", "ಏಕ ರಾಷ್ಟ್ರ ಏಕ ಪಡಿಗೆ ಪತ್ರ",
    "ಆತ್ಮನಿರ್ಭರ್ ಭಾರತ", "ಪಿಎಂ ಗತಿ ಶಕ್ತಿ", "ರಾಷ್ಟ್ರೀಯ ಶಿಕ್ಷಣ ನೀತಿ",
    "ಪಿಎಂ ಕೇರ್ಸ್ ಫಂಡ್", "ಪಿಎಂ ಸ್ವನಿಧಿ", "ಪ್ರಧಾನಮಂತ್ರಿ ಜನ್ ಧನ್ ಯೋಜನೆ",
    "ಕಿಸಾನ್ ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್", "ನಮಾಮಿ ಗಂಗೆ", "ಉಡಾನ್ ಯೋಜನೆ",
    "ಸೌಭಾಗ್ಯ ಯೋಜನೆ", "ಖೇಲೋ ಇಂಡಿಯಾ", "ಪಿಎಂ ಜನ್ ಔಷಧಿ ಯೋಜನೆ",
    "ಪಿಎಂ ವಿಶ್ವಕರ್ಮಾ ಯೋಜನೆ", "ವಂದೇ ಭಾರತ್ ಎಕ್ಸ್‌ಪ್ರೆಸ್",
    "ಅಮೃತ ಭಾರತ್", "ಪಿಎಂ ಪೋಷಣ್", "ಏಕ ಭಾರತ್ ಶ್ರೇಷ್ಠ ಭಾರತ್",
    "ಫಿಟ್ ಇಂಡಿಯಾ", "ಸಾಗರ್ಮಲಾ ಯೋಜನೆ", "ಭಾರತ್‌ಮಾಲಾ ಯೋಜನೆ",
    
    # Tamil - அனைத்து திட்டங்கள்
    "ஆயுஷ்மான் பாரத்", "பிஎம் கிசான்", "பிரதமர் கிசான் சம்மான் நிதி",
    "பிஎம் உஜ்வலா திட்டம்", "சுகாதார இந்தியா திட்டம்", "சுகாதார இந்தியா பணி",
    "அடல் ஓய்வூதிய திட்டம்", "டிஜிட்டல் இந்தியா", "மேக் இன் இந்தியா",
    "ஸ்மார்ட் நகர திட்டம்", "பிரதமர் வீட்டுவசதி திட்டம்",
    "பயிர் காப்பீடு திட்டம்", "ஜல் ஜீவன் பணி", "ஹர் கர் ஜல்",
    "மகாத்மா காந்தி தேசிய ஊரக வேலைவாய்ப்பு உத்தரவாத சட்டம்",
    "மனரேகா", "பிரதமர் முத்ரா திட்டம்", "ஸ்டாண்ட் அப் இந்தியா",
    "ஸ்டார்ட்அப் இந்தியா", "திறன் இந்தியா", "பெண் குழந்தைகளை காப்போம் படிப்போம்",
    "சுகன்யா சம்ரித்தி திட்டம்", "தேசிய சுகாதார பணி",
    "பிஎம் ஏழை நல உணவு திட்டம்", "ஒரு நாடு ஒரு ரேஷன் அட்டை",
    "சுயசார்பு இந்தியா", "பிஎம் கதி சக்தி", "தேசிய கல்வி கொள்கை",
    "பிஎம் கேர்ஸ் நிதி", "பிஎம் ஸ்வநிதி", "ஜன தன் திட்டம்",
    "கிசான் கடன் அட்டை", "நமாமி கங்கே", "உடான் திட்டம்",
    "சௌபாக்யா திட்டம்", "கேலோ இந்தியா", "ஜன் ஔஷதி திட்டம்",
    "வந்தே பாரத் எக்ஸ்பிரஸ்", "அம்ருத் பாரத்", "பிட் இந்தியா",
    
    # Telugu - అన్ని పథకాలు
    "ఆయుష్మాన్ భారత్", "పిఎం కిసాన్", "ప్రధాన మంత్రి కిసాన్ సమ్మాన్ నిధి",
    "పిఎం ఉజ్వలా యోజన", "స్వచ్ఛ భారత్ మిషన్", "స్వచ్ఛ భారత్ అభియాన్",
    "అటల్ పెన్షన్ యోజన", "డిజిటల్ ఇండియా", "మేక్ ఇన్ ఇండియా",
    "స్మార్ట్ సిటీ మిషన్", "ప్రధాన మంత్రి ఆవాస్ యోజన",
    "ఫసల్ బీమా యోజన", "జల్ జీవన్ మిషన్", "హర్ ఘర్ జల్",
    "మహాత్మా గాంధీ జాతీయ గ్రామీణ ఉపాధి హామీ చట్టం",
    "మన్రేగా", "ప్రధాన మంత్రి ముద్రా యోజన", "స్టాండ్ అప్ ఇండియా",
    "స్టార్టప్ ఇండియా", "స్కిల్ ఇండియా", "బేటీ బచావో బేటీ పడావో",
    "సుకన్య సమృద్ధి యోజన", "జాతీయ ఆరోగ్య మిషన్",
    "పిఎం గరీబ్ కళ్యాణ్ అన్న యోజన", "ఒక దేశం ఒక రేషన్ కార్డు",
    "ఆత్మ నిర్భర్ భారత్", "పిఎం గతి శక్తి", "జాతీయ విద్యా విధానం",
    "పిఎం కేర్స్ ఫండ్", "పిఎం స్వనిధి", "జన్ ధన్ యోజన",
    "కిసాన్ క్రెడిట్ కార్డ్", "నమమి గంగే", "ఉడాన్ యోజన",
    "సౌభాగ్య యోజన", "ఖేలో ఇండియా", "జన్ ఔషధి యోజన",
    "వందే భారత్ ఎక్స్‌ప్రెస్", "అమృత్ భారత్", "ఫిట్ ఇండియా",
    
    # Bengali - সকল প্রকল্প
    "আয়ুষ্মান ভারত", "পিএম কিসান", "প্রধানমন্ত্রী কিসান সম্মান নিধি",
    "পিএম উজ্জ্বলা যোজনা", "স্বচ্ছ ভারত মিশন", "স্বচ্ছ ভারত অভিযান",
    "অটল পেনশন যোজনা", "ডিজিটাল ইন্ডিয়া", "মেক ইন ইন্ডিয়া",
    "স্মার্ট সিটি মিশন", "প্রধানমন্ত্রী আবাস যোজনা",
    "ফসল বীমা যোজনা", "জল জীবন মিশন", "হর ঘর জল",
    "মহাত্মা গান্ধী জাতীয় গ্রামীণ কর্মসংস্থান গ্যারান্টি আইন",
    "মনরেগা", "প্রধানমন্ত্রী মুদ্রা যোজনা", "স্ট্যান্ড আপ ইন্ডিয়া",
    "স্টার্টআপ ইন্ডিয়া", "স্কিল ইন্ডিয়া", "বেটি বাঁচাও বেটি পড়াও",
    "সুকন্যা সমৃদ্ধি যোজনা", "জাতীয় স্বাস্থ্য মিশন",
    "পিএম গরিব কল্যাণ অন্ন যোজনা", "এক জাতি এক রেশন কার্ড",
    "আত্মনির্ভর ভারত", "পিএম গতি শক্তি", "জাতীয় শিক্ষা নীতি",
    "পিএম কেয়ার্স ফান্ড", "পিএম স্বনিধি", "জন ধন যোজনা",
    "কিসান ক্রেডিট কার্ড", "নমামি গঙ্গে", "উড়ান যোজনা",
    "সৌভাগ্য যোজনা", "খেলো ইন্ডিয়া", "জন ঔষধি যোজনা",
    "বন্দে ভারত এক্সপ্রেস", "অমৃত ভারত", "ফিট ইন্ডিয়া",
    
    # Malayalam, Marathi, Gujarati, Punjabi, Odia translations
    # (Continuing with major schemes in remaining languages...)
    "ആയുഷ്മാൻ ഭാരത്", "പിഎം കിസാൻ", "സ്വച്ഛ് ഭാരത് മിഷൻ",
    "डिजिटल इंडिया", "स्मार्ट सिटी मिशन", "प्रधानमंत्री आवास योजना",
    "આયુષ્માન ભારત", "પીએમ કિસાન", "સ્વચ્છ ભારત મિશન",
    "ਆਯੁਸ਼ਮਾਨ ਭਾਰਤ", "ਪੀਐਮ ਕਿਸਾਨ", "ਸਵੱਛ ਭਾਰਤ ਮਿਸ਼ਨ",
    "ଆୟୁଷ୍ମାନ ଭାରତ", "ପିଏମ କିସାନ", "ସ୍ୱଚ୍ଛ ଭାରତ ମିଶନ",
    
    # Additional schemes
    "Mission Indradhanush", "National Solar Mission", "POSHAN Abhiyaan",
    "UDAY Scheme", "DAY-NULM", "Swadesh Darshan", "HRIDAY",
    "AMRUT", "PM-KUSUM",
]

OFFICIALS = [
    # Constitutional Heads
    "President of India", "President", "Droupadi Murmu", "President Murmu", "Murmu",
    "Vice President", "Jagdeep Dhankhar", "VP Dhankhar", "Dhankhar",
    "Chief Justice of India", "CJI", "Chief Justice",
    
    # Prime Minister
    "Prime Minister", "PM", "Narendra Modi", "Modi", "PM Modi", "Shri Modi", "Mr Modi",
    
    # Key Cabinet Ministers (Current as of 2024-25)
    "Home Minister", "Amit Shah", "Shah", "HM Amit Shah",
    "Finance Minister", "Nirmala Sitharaman", "Sitharaman", "FM Sitharaman",
    "External Affairs Minister", "Foreign Minister", "S Jaishankar", "Jaishankar", "EAM Jaishankar",
    "Defence Minister", "Rajnath Singh", "Rajnath", "DM Rajnath Singh",
    "Road Transport Minister", "Nitin Gadkari", "Gadkari",
    "Railway Minister", "Ashwini Vaishnaw", "Vaishnaw",
    "Agriculture Minister", "Arjun Munda", "Munda",
    "Health Minister", "Mansukh Mandaviya", "Mandaviya",
    "Education Minister", "Dharmendra Pradhan", "Pradhan",
    "Petroleum Minister", "Hardeep Puri", "Puri",
    "Power Minister", "RK Singh",
    "Coal Minister", "Pralhad Joshi", "Joshi",
    "Civil Aviation Minister", "Jyotiraditya Scindia", "Scindia",
    "Labour Minister", "Bhupender Yadav", "Yadav",
    "I&B Minister", "Information Broadcasting Minister", "Anurag Thakur", "Thakur",
    "Environment Minister", "Bhupender Yadav",
    "Commerce Minister", "Piyush Goyal", "Goyal",
    "Textiles Minister", "Piyush Goyal",
    "Rural Development Minister", "Giriraj Singh",
    "Jal Shakti Minister", "Gajendra Singh Shekhawat", "Shekhawat",
    "Housing Minister", "Hardeep Puri",
    "Tourism Minister", "G Kishan Reddy", "Kishan Reddy",
    "Culture Minister", "G Kishan Reddy",
    "Law Minister", "Arjun Ram Meghwal", "Meghwal",
    "Parliamentary Affairs Minister", "Pralhad Joshi",
    "Skill Development Minister", "Dharmendra Pradhan",
    "MSME Minister", "Narayan Rane", "Rane",
    "Tribal Affairs Minister", "Arjun Munda",
    "Social Justice Minister", "Virendra Kumar",
    "Women Child Development Minister", "Smriti Irani", "Irani",
    "Minority Affairs Minister", "Mukhtar Abbas Naqvi", "Naqvi",
    "Food Processing Minister", "Pashupati Kumar Paras",
    "Steel Minister", "Jyotiraditya Scindia",
    "Chemicals Minister", "Mansukh Mandaviya",
    "Ports Minister", "Sarbananda Sonowal", "Sonowal",
    "AYUSH Minister", "Sarbananda Sonowal",
    
    # Other Key Positions
    "Attorney General", "Solicitor General", "Cabinet Secretary", "Principal Secretary to PM",
    "Chief Economic Adviser", "CEA", "Finance Secretary", "Home Secretary",
    "Foreign Secretary", "Defence Secretary", "Cabinet Secretary",
    "NITI Aayog CEO", "NITI Aayog Vice Chairman",
    "Election Commissioner", "Chief Election Commissioner", "CEC",
    "CAG", "Comptroller Auditor General",
    "National Security Adviser", "NSA", "Ajit Doval", "Doval",
    "Principal Scientific Adviser",
    
    # Hindi Names
    "राष्ट्रपति", "द्रौपदी मुर्मू", "मुर्मू",
    "उपराष्ट्रपति", "जगदीप धनखड़", "धनखड़",
    "प्रधानमंत्री", "पीएम", "नरेंद्र मोदी", "मोदी", "पीएम मोदी",
    "गृह मंत्री", "अमित शाह", "शाह",
    "वित्त मंत्री", "निर्मला सीतारमण", "सीतारमण",
    "विदेश मंत्री", "एस जयशंकर", "जयशंकर",
    "रक्षा मंत्री", "राजनाथ सिंह", "राजनाथ",
    "सड़क परिवहन मंत्री", "नितिन गडकरी", "गडकरी",
    "रेल मंत्री", "अश्विनी वैष्णव", "वैष्णव",
    "कृषि मंत्री", "अर्जुन मुंडा", "मुंडा",
    "स्वास्थ्य मंत्री", "मनसुख मंडाविया", "मंडाविया",
    "शिक्षा मंत्री", "धर्मेंद्र प्रधान", "प्रधान",
    "भारत के मुख्य न्यायाधीश",
    
    # Kannada Names
    "ರಾಷ್ಟ್ರಪತಿ", "ದ್ರೌಪದಿ ಮುರ್ಮು", "ಮುರ್ಮು",
    "ಉಪರಾಷ್ಟ್ರಪತಿ", "ಜಗದೀಪ್ ಧನ್ಖಡ್",
    "ಪ್ರಧಾನ ಮಂತ್ರಿ", "ಪಿಎಂ", "ನರೇಂದ್ರ ಮೋದಿ", "ಮೋದಿ",
    "ಗೃಹ ಸಚಿವ", "ಅಮಿತ್ ಶಾ", "ಶಾ",
    "ಹಣಕಾಸು ಸಚಿವ", "ನಿರ್ಮಲಾ ಸೀತಾರಾಮನ್", "ಸೀತಾರಾಮನ್",
    "ವಿದೇಶಾಂಗ ಸಚಿವ", "ಎಸ್ ಜೈಶಂಕರ್", "ಜೈಶಂಕರ್",
    "ರಕ್ಷಣಾ ಸಚಿವ", "ರಾಜನಾಥ್ ಸಿಂಗ್", "ರಾಜನಾಥ್",
    "ಭಾರತದ ಮುಖ್ಯ ನ್ಯಾಯಾಧೀಶ",
    
    # Tamil, Telugu, Bengali, Malayalam, Marathi, Gujarati, Punjabi, Odia Names
    "ஜனாதிபதி", "த்ரௌபதி முர்மு", "பிரதமர்", "நரேந்திர மோடி", "மோடி",
    "రాష్ట్రపతి", "ద్రౌపది ముర్ము", "ప్రధాన మంత్రి", "నరేంద్ర మోదీ", "మోదీ",
    "রাষ্ট্রপতি", "দ্রৌপদী মুর্মু", "প্রধানমন্ত্রী", "নরেন্দ্র মোদী", "মোদী",
    "രാഷ്ട്രപതി", "ദ്രൗപതി മുർമു", "പ്രധാനമന്ത്രി", "നരേന്ദ്ര മോദി", "മോദി",
    "राष्ट्रपती", "द्रौपदी मुर्मू", "पंतप्रधान", "नरेंद्र मोदी", "मोदी",
    "રાષ્ટ્રપતિ", "દ્રોપદી મુર્મુ", "વડાપ્રધાન", "નરેન્દ્ર મોદી", "મોદી",
    "ਰਾਸ਼ਟਰਪਤੀ", "ਦ੍ਰੌਪਦੀ ਮੁਰਮੂ", "ਪ੍ਰਧਾਨ ਮੰਤਰੀ", "ਨਰਿੰਦਰ ਮੋਦੀ", "ਮੋਦੀ",
    "ରାଷ୍ଟ୍ରପତି", "ଦ୍ରୌପଦୀ ମୁର୍ମୁ", "ପ୍ରଧାନମନ୍ତ୍ରୀ", "ନରେନ୍ଦ୍ର ମୋଦୀ", "ମୋଦୀ",
    
    # Generic titles
    "Union Minister", "Cabinet Minister", "Minister of State",
    "Chief Secretary", "Principal Secretary", "Additional Secretary", "Joint Secretary",
    "Governor", "Lieutenant Governor", "District Collector", "District Magistrate", "Commissioner",
]

# Regional variations of state/city names (for multilingual support)
REGIONAL_VARIATIONS = {
    # Hindi variations
    "भारत": "India",
    "दिल्ली": "Delhi",
    "मुंबई": "Mumbai",
    "कोलकाता": "Kolkata",
    "चेन्नई": "Chennai",
    "बेंगलुरु": "Bangalore",
    "हैदराबाद": "Hyderabad",
    "पुणे": "Pune",
    "अहमदाबाद": "Ahmedabad",
    "जयपुर": "Jaipur",
    
    # Tamil variations
    "இந்தியா": "India",
    "டெல்லி": "Delhi",
    "மும்பை": "Mumbai",
    "கொல்கத்தா": "Kolkata",
    "சென்னை": "Chennai",
    "பெங்களூர்": "Bangalore",
    
    # Kannada variations
    "ಭಾರತ": "India",
    "ದೆಹಲಿ": "Delhi",
    "ಮುಂಬೈ": "Mumbai",
    "ಬೆಂಗಳೂರು": "Bangalore",
    "ಹೈದರಾಬಾದ್": "Hyderabad",
    
    # Telugu variations
    "భారతదేశం": "India",
    "ఢిల్లీ": "Delhi",
    "ముంబై": "Mumbai",
    "హైదరాబాద్": "Hyderabad",
    "బెంగళూరు": "Bangalore",
    
    # Bengali variations
    "ভারত": "India",
    "দিল্লি": "Delhi",
    "মুম্বাই": "Mumbai",
    "কলকাতা": "Kolkata",
    "চেন্নাই": "Chennai",
    
    # Gujarati variations
    "ભારત": "India",
    "દિલ્હી": "Delhi",
    "મુંબઈ": "Mumbai",
    "અમદાવાદ": "Ahmedabad",
    
    # Marathi variations
    "भारत": "India",
    "दिल्ली": "Delhi",
    "मुंबई": "Mumbai",
    "पुणे": "Pune",
}

# Major Indian cities
MAJOR_CITIES = [
    "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata",
    "Surat", "Pune", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane",
    "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad", "Patna", "Vadodara", "Ghaziabad",
    "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivali",
    "Vasai-Virar", "Varanasi", "Srinagar", "Aurangabad", "Dhanbad", "Amritsar",
    "Navi Mumbai", "Allahabad", "Ranchi", "Howrah", "Coimbatore", "Jabalpur",
    "Gwalior", "Vijayawada", "Jodhpur", "Madurai", "Raipur", "Kota", "Chandigarh",
    "Guwahati", "Thiruvananthapuram", "Bhubaneswar", "Mysore", "Kochi"
]
